#! ANSIBLE_STDOUT_CALLBACK=yaml ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_ROLES_PATH=~/Desktop/k8s/ansible-roles/ ansible-playbook -i ansible-deployment-example/inventory.yaml --tags=helm_deploy
# --tags helm_deploy

---
# ---
# -----------------------------------------------------------------
- name: Deploy k3s via external role
  hosts: all
  tags: [k3s]
  become: true

  # --- This defines the kubeconfig_root variable
  # -----------------------------------------------------------------
  # --- install k8s and configure the cluster
  # --- using https://github.com/pfisterer/k3s-dhbw-cloud-role
  roles:
    - role: k3s-dhbw-cloud-role
    
  tasks:
    # -----------------------------------------------------------------
    # ClusterRoleBinding for ServiceAccount (rds-admin-binding)
    # -----------------------------------------------------------------
    - name: Ensure rds-admin-binding ClusterRoleBinding exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: rds-admin-binding
          subjects:
            # Grant access to the default ServiceAccount in the default namespace
            - kind: ServiceAccount
              name: default
              namespace: default
          roleRef:
            kind: ClusterRole
            name: cluster-admin # The highest level of access
            apiGroup: rbac.authorization.k8s.io
        kubeconfig: "{{ kubeconfig_root }}"

    # -----------------------------------------------------------------
    # Add helm repos
    # -----------------------------------------------------------------

    - name: Ensure all necessary Helm repositories are present
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
        state: present
      loop:
        - { name: keel, url: https://charts.keel.sh }
        - { name: cloudnative-pg, url: https://cloudnative-pg.io/charts }

    # -----------------------------------------------------------------
    # --- Postgres Operator
    # -----------------------------------------------------------------

    - name: Install or upgrade CloudNativePG Operator
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_root }}"
        name: cloudnative-pg
        chart_ref: cloudnative-pg/cloudnative-pg
        release_namespace: default
        wait: true
        atomic: true
      tags: [cloud-native-pg]

    # -----------------------------------------------------------------
    # --- Keel
    # -----------------------------------------------------------------

    - name: Install or upgrade Keel
      kubernetes.core.helm:
        name: keel
        chart_ref: keel/keel
        release_namespace: default
        kubeconfig: "{{ kubeconfig_root }}"
        state: present
        wait: true
        atomic: true

    # -----------------------------------------------------------------
    # --- Copy Helm Chart to Remote
    # -----------------------------------------------------------------
    - name: Copy Helm chart directory to remote
      ansible.posix.synchronize:
        src: "helm-chart"
        dest: "/root/"
        archive: true
        delete: true
        rsync_opts:
          - "--chown=root:root"
      tags: [helm_deploy]

    # -----------------------------------------------------------------
    # --- Create Helm Values File from Ansible Variables
    # -----------------------------------------------------------------
    - name: Create Helm values file from template
      ansible.builtin.template:
        src: helm-values.yaml.j2
        dest: "/root/helm-values.yaml"
        owner: root
        group: root
        mode: "0644"
      tags: [helm_deploy]

    # -----------------------------------------------------------------
    # --- Deploy with Helm Chart
    # -----------------------------------------------------------------
    - name: Deploy pdns-cloud Helm chart
      kubernetes.core.helm:
        name: cloud-self-service
        chart_ref: /root/helm-chart
        release_namespace: default
        kubeconfig: "{{ kubeconfig_root }}"
        values_files:
          - /root/helm-values.yaml
        state: present
        atomic: true
      tags: [helm_deploy]
