apiVersion: v2
name: dynamic-zones
description: Self-service DNS zone management on top of PowerDNS
type: application
version: 0.8.0
appVersion: "0.8.0"
maintainers:
  - name: Dennis Pfisterer
    email: dennis.pfisterer@dhbw.de
