{{- if not .Values.dynamicZonesAPI.existingSecret }}
{{- $comp := dict "context" . "component" "dynamic-zones" -}}
{{- $name := include "cloud-self-service.componentName" $comp -}}
{{- $labels := include "cloud-self-service.labels" $comp -}}
{{- $pgHost := .Values.dynamicZonesAPI.database.hostname -}}
{{- $pgUser := .Values.dynamicZonesAPI.database.username -}}
{{- $pgPass := .Values.dynamicZonesAPI.database.password -}}
{{- $pgDB := .Values.dynamicZonesAPI.database.name -}}
{{- $defaultConn := printf "host=%s user=%s password=%s dbname=%s port=5432 sslmode=disable" $pgHost $pgUser $pgPass $pgDB -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: {{ default $defaultConn .Values.dynamicZonesAPI.database.connectionString | quote }}
  pdns-api-key: {{ .Values.powerDNS.apiKey | trim | quote }}
  upstream-tsig-secret: {{ .Values.dynamicZonesAPI.upstreamDNS.tsigSecret | default "" | quote }}
  zone-admin-tsig-key: {{ .Values.dynamicZonesAPI.zoneDefaults.defaultAdminTsigKey | default "" | quote }}
{{- end }}
